site_name: Hexplain AI
site_url: https://yourdomain.com

theme:
  name: material
  features:
    - navigation.instant
    - header.autohide
    - navigation.footer
  palette:
    primary: teal
    accent: cyan
  logo: images/logo.png
  custom_dir: overrides
  favicon: images/logo.png

extra_css:
  - styles/hero.css

plugins: []

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption